server {
    server_name supplax.loc;
    root /var/www/html/public;

    index index.php;

    client_max_body_size 64M;

    charset utf-8;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~ ^/(config|templates|var|src|bin)/.*\.(php|yml|yaml|xml|ini)$ {
        deny all;
        return 404;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        internal;
    }

    location ~ \.php$ {
        deny all;
        return 404;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        log_not_found off;
    }

    error_log /var/log/nginx/supplax_error.log;
    access_log /var/log/nginx/supplax_access.log;
}